version: 1
metadata:
  authors: "Maintained by the Vapor Core Team with hundreds of contributions from the Vapor Community."
external_links:
  documentation: "https://docs.vapor.codes/leaf/getting-started/"