#if !canImport(ObjectiveC)
import XCTest

extension LeafTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LeafTests = [
        ("testStub", testStub),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LeafTests.__allTests__LeafTests),
    ]
}
#endif
