name: issue-to-project-board-workflow
on:
  # Trigger when an issue gets labeled or deleted
  issues:
    types: [reopened, closed, labeled, unlabeled, assigned, unassigned]

jobs:
  update_project_boards:
    name: Update project boards
    uses: vapor/ci/.github/workflows/update-project-boards-for-issue.yml@main
    secrets: inherit
